### ISSUE TITLE
Staticcheck

### ISSUE THREAD

**Issue by Pesa** [usnistgov/ndn-dpdk#12]
Please consider using [Staticcheck](https://staticcheck.io/) if it makes sense.

**Comment by yoursunny** [comment]
staticcheck is provided by default in VSCode Go extension.
I don't plan to invoke it in CI yet because there are false positives around cgo code.

**Comment by Pesa** [comment]
> staticcheck is provided by default in VSCode Go extension.

That cannot be enforced.

> I don't plan to invoke it in CI yet because there are false positives around cgo code.

Can the checks that trigger false positives be disabled?

**Comment by yoursunny** [comment]
> > staticcheck is provided by default in VSCode Go extension.
> 
> That cannot be enforced.

I am effectively the only developer, and I use VSCode with Go extension.
Problematic code flagged by the linter appears yellow or red in VSCode, and I pay attention to them.

> > I don't plan to invoke it in CI yet because there are false positives around cgo code.
> 
> Can the checks that trigger false positives be disabled? (assuming they're not too many)

There are still dozens.
Some are being fixed since last year, such as missing godoc.

**Comment by yoursunny** [comment]
> I don't plan to invoke it in CI yet because there are false positives around cgo code.

Apparently the cgo false positives are coming from the **vet** tool.

**staticcheck** flagged about 20 issues.
Most of them are legitimated and are being fixed.

**Comment by yoursunny** [comment]
Merged in 80e3b97428042aa4100e1a89bafd3848e4fa4fad
