### ISSUE TITLE
Docker permission denied while trying to connect to the Docker daemon socket (solved)

### ISSUE THREAD

**Issue by Code-shaker** [usnistgov/ndn-dpdk#17]
```text
GQLSERVER=$(docker inspect -f 'http://{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}:3030/' ndndpdk-svc)
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/ndndpdk-svc/json: dial unix /var/run/docker.sock: connect: permission denied
```
Run this command in your favourite shell and then completely log out of your account and log back in (or exit your SSH session and reconnect, if in doubt, reboot the computer you are trying to run docker on!)

`sudo usermod -a -G docker $USER`

done

**Comment by Code-shaker** [comment]
After I execute `sudo ndndpdk-ctrl activate-forwarder`
output: Hint: pass parameters via stdin

Ok, should be something else changed after this?

sudo ndndpdk-ctrl create-ether-face
[sudo] password for vmadmin: 
NAME:
   ndndpdk-ctrl create-ether-face - Create an Ethernet face

USAGE:
   ndndpdk-ctrl create-ether-face [command options] [arguments...]

CATEGORY:
   face

OPTIONS:
   --port port       DPDK port name (default: search by local MAC address)
   --port-mtu MTU    port MTU (excluding Ethernet headers) (default: hardware default)
   --mtu MTU         face MTU (excluding all headers) (default: maximum)
   --max-rxq value   maximum number of RX queues (default: 1)
   --local address   local MAC address
   --remote address  remote MAC address (default: 01:00:5e:00:17:aa)
   --vlan VLAN       VLAN identifier (default: no VLAN)
   --help, -h        show help (default: false)
   
2021/07/18 12:08:24 Required flag "local" not set

**Comment by yoursunny** [comment]
> sudo ndndpdk-svc

If you built NDN-DPDK Docker image [from these instructions](https://github.com/usnistgov/ndn-dpdk/blob/1c9ce3a328284312d3fe128eae872d43bb7595f5/docs/Docker.md), you should never invoke `ndndpdk-svc` command directly.
The same page has instructions on how to start and stop the container.

I'm aware that someone else has published binary NDN-DPDK images on Docker Hub.
If you are using one of these, please contact the publisher for support.

> Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock

You must add your user account to the `docker` group.
See [Manage Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user).

> How to restart the process to activate forwarder again?

Delete the container and start a new container.

**Comment by Code-shaker** [comment]
ohh sry i didn't see your answer I have changed something
