### ISSUE TITLE
run (ndn-cxx) NFD alongside NDN-DPDK on the same machine

### ISSUE THREAD

**Issue by Code-shaker** [usnistgov/ndn-dpdk#19]
how to intergrate an application on NDN-DPDK(NFD)?

**Comment by yoursunny** [comment]
It is possible to run both NDN-DPDK and NFD on the same machine.
See **NDN-DPDK interoperability with other NDN software** page.
Prefix registration, etc, has to be performed manually.

If you are developing a new app, you should use NDNgo (part of this repository) or [NDNts](https://yoursunny.com/p/NDNts/) libraries. They have better integration with NDN-DPDK.

**Comment by Code-shaker** [comment]
I want to write an application, which permitted different video chunks, recieve interest and transmit data. I saw your NDNts-video, didn't know what would be more useful.

**Comment by yoursunny** [comment]
> receive interest and transmit data

So it's a producer.
The producer component of NDNts-video is in [yoursunny/NDNts-video-server](https://github.com/yoursunny/NDNts-video-server).
Specifically, the `serve` subcommand.

If you want to connect NDNts-video-server to NDN-DPDK forwarder, you can replace `await openUplinks();` with something like:

```ts
// at top of the module; of course, you need to install this package first
import { openFace } from "@ndn/dpdkmgmt";

// in place of `openUplinks()`
await openFace({
  localHost: "172.26.6.3", // IPv4 address of the NDNts-video-server container
  gqlServer: "http://172.26.6.3:3030", // GraphQL endpoint of NDN-DPDK
});
```

The consumer component of NDNts-video only runs in a browser.
Browsers can only communicate via WebSockets and HTTP/3 (WebTransport), but neither is supported in NDN-DPDK.
Therefore, it would not work with NDN-DPDK.

---

NDN-DPDK is designed to provide high aggregate throughput: you can have hundreds of hosts each running NFD/YaNFD along with applications, and they all connect to a router powered by NDN-DPDK.

While NDNts and NDNgo can enable applications connect directly to NDN-DPDK, neither library would unlock the full potential throughput of NDN-DPDK.
You might get 1~5 Gbps out of these libraries (not benchmarked!), but if you want to run a large video site, you'll need to invest in your own library, using the existing libraries as a reference.

**Comment by Code-shaker** [comment]
so NDNts is not praticle, thats why I should work with NDNgo?

**Comment by Code-shaker** [comment]
what would you rather suggest to use?

**Comment by Code-shaker** [comment]
I want adapt the data-transfer from a web conferencing application with NDN-DPDK

**Comment by yoursunny** [comment]
> web conferencing application with NDN-DPDK

NDN-DPDK is not the right product for this use case, because it isn't possible to connect a browser to NDN-DPDK.
You should look into the combination of NFD and [NDN QUIC gateway](https://github.com/yoursunny/NDN-QUIC-gateway), and then your app can connect to NDN network over QUIC using [WebTransport API](https://web.dev/webtransport).

You can of course use NDN-DPDK at the network core to interconnect NFD instances and achieve higher throughput.

**Comment by yoursunny** [comment]
> If you want to connect NDNts-video-server to NDN-DPDK forwarder, you can replace `await openUplinks();` with something like:

I just did some updates in NDNts (commit https://github.com/yoursunny/NDNts/commit/10ed9fa0ebcc675a4fb719a1caa00e171bead35c): NDN-DPDK connection is integrated into the `@ndn/cli-common` package.
No code modification is needed to connect to NDN-DPDK from a NDNts app that uses `@ndn/cli-common` package.
See https://github.com/yoursunny/NDNts-video-server/issues/3#issuecomment-901576814 for more information.

**Comment by Code-shaker** [comment]
"https://github.com/remap/ndnrtc" is written in c++, so its also not compatible with NDN-DPDK? Therefore I would use "https://github.com/keroserene/go-webrtc" or what do you suggest?

**Comment by yoursunny** [comment]
> "https://github.com/remap/ndnrtc" is written in c++, so its also not compatible with NDN-DPDK?

NDN-RTC uses [NDN-CPP](https://github.com/named-data/ndn-cpp) that is labeled OBSOLETE.
It is compatible with neither (current version of) NFD nor NDN-DPDK.

> Therefore I would use "https://github.com/keroserene/go-webrtc" or what do you suggest?

This is also unmaintained according to README, but you can use its successor [Pion WebRTC](https://github.com/pion/webrtc).
Pion implements the WebRTC standard, so you need to come up with the NDN protocols.

**Comment by Code-shaker** [comment]
With which steps to use the NDN-DPDK for livestreaming at the network core, to got better troughput and performance?

get trough:
[NDN QUIC gateway](https://github.com/yoursunny/NDN-QUIC-gateway)
`NFD` embedded
[Pion WebRTC](https://github.com/pion/webrtc)

**Comment by yoursunny** [comment]
It would be something like:

```
    50x                5x              50x                     500x
              one per continent     in major cities
|---------|        |--------|       |------------|           |------|
|streamer | 10Gbps |        | 1Gbps | NFD router | last mile |viewer|
|         |--------|NDN-DPDK|-------|            |-----------|      |
|local NFD|        | router |       |QUIC gateway|           |webapp|
|---------|        |--------|       |------------|           |------|
                 10Gbps among
                 NDN-DPDK routers
```

You should get your application working with NFD and NDN-QUIC-gateway, before adding NDN-DPDK.
If your scale is smaller than the above, adding NDN-DPDK would not bring substantial benefits.

**Comment by Code-shaker** [comment]
thanks for your fast answer, yes I will work and prepare it further
