### ISSUE TITLE
run test NDNgo application

### ISSUE THREAD

**Issue by Code-shaker** [usnistgov/ndn-dpdk#20]
How to run given application from "https://github.com/usnistgov/ndn-dpdk/tree/main/app"

**Comment by Code-shaker** [comment]
or use "https://github.com/usnistgov/ndn-dpdk/tree/main/ndn/endpoint"?

**Comment by Code-shaker** [comment]
I already use "https://github.com/usnistgov/ndn-dpdk/tree/main/cmd/ndndpdk-godemo#endpoint-api" without problems

**Comment by yoursunny** [comment]
Files in `ndn-dpdk/app` directory do not build to executables, so you cannot run them directly.
They provide internal API for commands in `ndn-dpdk/cmd/*` directory, which are built as executables in `ndn-dpdk/build/bin` and you can execute them.
The directory name `app` indicates they (loosely) belong to application level, and does not imply they are executable.

**Comment by Pesa** [comment]
To be fair, the description in README.md:

> app: applications, including the forwarder dataplane

is rather misleading.

**Comment by Code-shaker** [comment]
How to start with some examples on NDN-DPDK? Sry I have to pratice and to understand many coherences, before writing some useful code. So far I found something on: "https://github.com/go-ndn/example"

**Comment by yoursunny** [comment]
> How to start with some examples on NDN-DPDK?

See `ndn-dpdk/cmd/ndndpdk-godemo` command.

> I found something on: "https://github.com/go-ndn/example"

This is incompatible with NDN-DPDK.

**Comment by Code-shaker** [comment]
Ok I see

But how does you build them, after you are ready with coding? just `go install`?

**Comment by yoursunny** [comment]
> how does you build them

`ndndpdk-godemo` is built together with NDN-DPDK itself when you execute `make`, and the executable is in `ndn-dpdk/build/bin` folder.

If you are writing new program using NDNgo library, it will support normal `go get` and `go install` workflow.

**Comment by yoursunny** [comment]
I also verified that `ndndpdk-godemo` can be installed with `go install` command:

```bash
go install github.com/usnistgov/ndn-dpdk/cmd/ndndpdk-godemo@latest
```

**Comment by yoursunny** [comment]
> To be fair, the description in README.md:
> 
> > app: applications, including the forwarder dataplane
> 
> is rather misleading.

This is changed to "application level modules".
