### ISSUE TITLE
EthDev not found

### ISSUE THREAD

**Issue by aonrdbit** [usnistgov/ndn-dpdk#26]
Hello, in the ndnping example of forward.md, is the mac address of the local parameter after the ndndpdk-ctrl create-ether-face command the mac address that is bound to the network card? If so, an "EthDev not found" error will be displayed ; If not, which network card's mac address should be? Sincerely look forward to your answer, thank you.

**Comment by yoursunny** [comment]
Did you install NDN-DPDK as a systemd service or a Docker container?
If it's a Docker container, did you add `--device` flags in `docker run` command?

Did you remember to *activate* the forwarder before trying to create a face?

What's the brand and model of your Ethernet adapter?

What's the output of `dpdk-devbind.py --status-dev net` command?
Do you see the intended Ethernet adapter there?

Is there any other error messages in NDN-DPDK service logs?
You can see them with `ndndpdk-ctrl systemd logs` or `docker logs ndndpdk-svc`.

**Comment by aonrdbit** [comment]
Thanks for your quick reply. I am sorry that I did not clarify my question. 
I did not use docker. I have successfully started ndn-dpdk and activated it as a forwarder. Below is the output of my dpdk-devbind.py. If you use the mac address of the bound network card, the error "EthDev not found" will appear, and the ifconfig command does not have this network card information. 
In addition, I started the service by running ndndpdk-svc instead of ndndpdk-ctrl systemd start. Is there a problem?
![2021-09-22 21-07-16屏幕截图](https://user-images.githubusercontent.com/34164349/134350025-df7dcb43-bd25-47b0-b744-3e9cdd9a97c4.png)

**Comment by yoursunny** [comment]
Please provide all requested information in textual format, not as pictures.

**Comment by aonrdbit** [comment]
I found my mistake, thank you for your patient answers.

**Comment by yoursunny** [comment]
Can you explain what's the mistake, to help other users?

**Comment by aonrdbit** [comment]
I ignored the ".eal.pciDevices" parameter, just add the bound network card to this parameter.
