### ISSUE TITLE
Make liburing dependency optional

### ISSUE THREAD

**Issue by Pesa** [usnistgov/ndn-dpdk#27]
It shouldn't be needed if all I want is the forwarder functionality.

**Comment by yoursunny** [comment]
liburing is a small library that can be easily compiled in all supported platforms.
Trying to make it into a build constraint would complicate every invocation of the Go compiler (it needs a `-tag`).
Moreover, the forwarder may start to use liburing for Unix socket faces in the future.
Therefore, I consider this WONTFIX.
