### ISSUE TITLE
Containernet and ndn dpdk container

### ISSUE THREAD

**Issue by rohansuri1996** [usnistgov/ndn-dpdk#38]
Hi, 

I am trying to use ndn dpdk containers as host for containernet (fork of mininet which allows docker containers as hosts, https://containernet.github.io/)

The problem is I have no access to the ndn controller (container ip:3030) once I start the containernet topology. Below is the topology.py (python3 topology.py to start this topology, note: docker and containernet should be installed)

```python
#!/usr/bin/python
"""
This is the most simple example to showcase Containernet.
"""
from mininet.net import Containernet
from mininet.node import Controller
from mininet.cli import CLI
from mininet.link import TCLink
from mininet.log import info, setLogLevel
setLogLevel('info')
net = Containernet(controller=Controller)
info('*** Adding controller\n')
net.addController('c0')
info('*** Adding docker containers\n')
d1 = net.addDocker('d1',volumes=["run-ndn:/run/ndn"], ip='10.0.0.251', dimage="ndn-dpdk", dcmd= "/usr/local/bin/ndndpdk-svc" ,ports=[3030], port_bindings={3030:3030}, publish_all_ports=True)
d2 = net.addDocker('d2', volumes=["run-ndn:/run/ndn"],ip='10.0.0.252', dimage="ndn-dpdk",dcmd= "/usr/local/bin/ndndpdk-svc" , ports=[3030], port_bindings={3030:3031}, publish_all_ports=True)
info('*** Adding switches\n')
s1 = net.addSwitch('s1')
s2 = net.addSwitch('s2')
info('*** Creating links\n')
net.addLink(d1, s1)
net.addLink(s1, s2, cls=TCLink, delay='100ms', bw=1)
net.addLink(s2, d2)
info('*** Starting network\n')
net.start()
info('*** Testing connectivity\n')
net.ping([d1, d2])
info('*** Running CLI\n')
CLI(net)
info('*** Stopping network')
net.stop()
```

d1 and d2 are the hosts. I understand its not fully the issue of ndn image but Idk where else to find the solution for this problem. I think its the problem because i cannot pass the flags in the d1 and d2 (restart on failure, cap-add, mounts). 

Thanks in advance. I am a student of TU Ilmenau, Germany who is trying to make a topology with ndn containers on containernet to perform some experiments.

**Comment by yoursunny** [comment]
> `dcmd= "/usr/local/bin/ndndpdk-svc"`

By default, `ndndpdk-svc` only listens on `http://127.0.0.1:3030`, so that you cannot get to it via Docker networking.
Change the command line to `/usr/local/bin/ndndpdk-svc --gqlserver http://:3030` and it would become accessible.
This is also the [CMD specified in the normal Dockerfile](https://github.com/usnistgov/ndn-dpdk/blob/a27140881992ad8e2d7974399f337fe9f86bba9b/Dockerfile#L50).

**Comment by yoursunny** [comment]
Since you are the second one asking about Containernet, I tried it and got a simple scenario working.

* hardware: [Utah Emulab d710](https://gitlab.flux.utah.edu/emulab/emulab-devel/-/wikis/Utah-Cluster/d710s)
* Containernet version 904b180b0b5d28ffdc3cbe7924d37d3c37e02517
* NDN-DPDK version a27140881992ad8e2d7974399f337fe9f86bba9b
* NDN-DPDK Docker image built with `docker build --build-arg DEPENDS_ARGS="--arch=nehalem" --build-arg MAKE_ENV="NDNDPDK_MK_RELEASE=1 NDNDPDK_MK_THREADSLEEP=1" -t ndn-dpdk .`
* Extra dependency: `sudo pip3 install py2graphql` (version 0.14.5)

```python
#!/usr/bin/python
import sys
import subprocess
from py2graphql import Client
from mininet.net import Containernet
from mininet.node import Controller
from mininet.cli import CLI
from mininet.link import TCLink
from mininet.log import info, setLogLevel

setLogLevel('info')
net = Containernet(controller=Controller)

info('*** Configuring hugepages\n')
subprocess.run('while ! dpdk-hugepages.py --setup 8G; do sleep 1; done',
               shell=True, check=True, stdout=sys.stdout, stderr=sys.stderr)

info('*** Configuring Docker volumn\n')
subprocess.run('docker volume create run-ndn', shell=True,
               check=True, stdout=sys.stdout, stderr=sys.stderr)

info('*** Adding controller\n')
net.addController('c0')

info('*** Adding docker containers\n')
NDN_DPDK_KWARGS = dict(
    dimage='ndn-dpdk',
    dcmd='/usr/local/bin/ndndpdk-svc --gqlserver http://:3030',
    volumes=['run-ndn:/run/ndn'],
    cap_add=['IPC_LOCK', 'NET_ADMIN', 'SYS_ADMIN', 'SYS_NICE']
)
dP = net.addDocker('P', ip='10.58.13.1/24', **NDN_DPDK_KWARGS)
dQ = net.addDocker('Q', ip='10.58.13.2/24', **NDN_DPDK_KWARGS)

info('*** Adding switches\n')
s1 = net.addSwitch('s1')
s2 = net.addSwitch('s2')

info('*** Creating links\n')
lP = net.addLink(dP, s1, addr1='02:60:18:6d:b0:10')
net.addLink(s1, s2, cls=TCLink, delay='100ms', bw=1)
lQ = net.addLink(dQ, s2, addr1='02:60:18:6d:b0:20')

info('*** Starting network\n')
net.start()
for link in [lP, lQ]:
    link.intf1.cmd(['ip', 'link', 'set', link.intf1.name, 'up'])

cP = Client(url='http://%s:3030' %
            dP.dcinfo['NetworkSettings']['IPAddress'], headers={})
cQ = Client(url='http://%s:3030' %
            dQ.dcinfo['NetworkSettings']['IPAddress'], headers={})

info('*** Activating NDN-DPDK\n')
for client in [cP, cQ]:
    result = client.fetch("""
        mutation activate($arg: JSON!) {
            activate(forwarder: $arg)
        }
    """, {
        'arg': {
            'eal': {
                'lcoresPerNuma': {'1': 6},
                'memPerNuma': {'1': 4096}
            },
            'mempool': {
                'DIRECT': {'capacity': 65535, 'dataroom': 9128},
                'INDIRECT': {'capacity': 65535},
                'PAYLOAD': {'capacity': 65535, 'dataroom': 9128}
            }
        }
    })
    info('activate result %s\n' % result)

info('*** Creating faces and FIB entries\n')
faceP = cP.fetch("""
    mutation createFace($locator: JSON!) {
        createFace(locator: $locator) {
            id
        }
    }
""", {
    'locator': {
        'scheme': 'ether',
        'local': '02:60:18:6d:b0:10',
        'remote': '02:60:18:6d:b0:20'
    }
})
info('faceP result %s\n' % faceP)
if 'error' not in faceP:
    fibPQ = cP.fetch("""
        mutation insertFibEntry($name: Name!, $nexthops: [ID!]!) {
            insertFibEntry(name: $name, nexthops: $nexthops) {
                id
            }
        }
    """, {
        'name': '/Q',
        'nexthops': [faceP['data']['createFace']['id']]
    })
    info('fibPQ result %s\n' % fibPQ)
faceQ = cQ.fetch("""
    mutation createFace($locator: JSON!) {
        createFace(locator: $locator) {
            id
        }
    }
""", {
    'locator': {
        'scheme': 'ether',
        'local': '02:60:18:6d:b0:20',
        'remote': '02:60:18:6d:b0:10'
    }
})
info('faceQ result %s\n' % faceQ)
if 'error' not in faceQ:
    fibQP = cQ.fetch("""
        mutation insertFibEntry($name: Name!, $nexthops: [ID!]!) {
            insertFibEntry(name: $name, nexthops: $nexthops) {
                id
            }
        }
    """, {
        'name': '/P',
        'nexthops': [faceQ['data']['createFace']['id']]
    })
    info('fibQP result %s\n' % fibQP)

info('*** Starting producer\n')
dP.popen('ndndpdk-godemo pingserver --name /P', shell=True)
dQ.popen('ndndpdk-godemo pingserver --name /Q', shell=True)

info("""*** Running CLI
Try:
    P ndndpdk-godemo pingclient --name /Q
    Q ndndpdk-godemo pingclient --name /P
""")
CLI(net)

info('*** Stopping network\n')
net.stop()
```

**Comment by rohansuri1996** [comment]
Hi,
Thanks for writing back to me. I have tested the code. 
1. The first error was my script wasn't able to find ndn-hugepages.py  I fixed it by manually assigning hugepages.

2. The 2nd error which I am getting is what I am not able to fix-

*** Starting 2 switches
s1 (1.00Mbit 100ms delay) s2 (1.00Mbit 100ms delay) ...(1.00Mbit 100ms delay) (1.00Mbit 100ms delay) 
*** Activating NDN-DPDK
activate result {'data': None, 'errors': [{'message': 'rte_eal_init 13 Permission denied', 'locations': [{'line': 3, 'column': 13}], 'path': ['activate']}]}
activate result {'data': None, 'errors': [{'message': 'rte_eal_init 13 Permission denied', 'locations': [{'line': 3, 'column': 13}], 'path': ['activate']}]}
*** Creating faces and FIB entries
faceP result {'data': None, 'errors': [{'message': 'createFace is disallowed; is NDN-DPDK forwarder activated?', 'locations': [{'line': 3, 'column': 9}], 'path': ['createFace']}]}
Traceback (most recent call last):
  File "ndnexperiment.py", line 99, in <module>
    'nexthops': [faceP['data']['createFace']['id']]
TypeError: 'NoneType' object is not subscriptable

Is there something I am still doing wrong?

3.  Also, I see you also have a multiverse controller which I would also like to experiment and connect to our containernet topology in which the ndp dpdk would be the host. I was able to use ONOS as the controller in the past. Basically I am trying to build a load balancer on this architecture. So my other question is is there a way to connect the multiverse controller to containernet so that we can experiment on bigger topologies.

As mentioned above thanks for the help.

**Comment by yoursunny** [comment]
> my script wasn't able to find ndn-hugepages.py

It's called `dpdk-hugepages.py`.
You need to extract this script from the NDN-DPDK container image.
See "NDN-DPDK Docker container" page "prepare the host machine" section.

---

> activate result {'data': None, 'errors': [{'message': 'rte_eal_init 13 Permission denied', 'locations': [{'line': 3, 'column': 13}], 'path': ['activate']}]}

NDN-DPDK activation failed.
You can see more information by looking at logs:

```bash
docker logs mn.P
docker logs mn.Q
```

As stated above:

> Emulab d710 is a somewhat unusual machine that has NUMA socket 1 but not NUMA socket 0.
> For machine that has NUMA socket 0 instead of NUMA socket 1, you need to change the activation parameter to `'lcoresPerNuma': {'0': 6}, 'memPerNuma': {'0': 4096}`.

You can see your NUMA sockets with `lscpu` command.

---

> multiverse controller 

Please ask Multiverse controller questions in their repository: https://github.com/multiverse-nms/multiverse-controller

**Comment by rohansuri1996** [comment]
Hi again,
I am still getting errors. I have installed the dependency and also prepared the host machine.
I would also like to mention my machine has 

> Numa 0 and Intel® Xeon(R) CPU E5-1620 v3 @ 3.50GHz × 8 with 126GB of Memory.

 Can be there some driver issues that I am missing?

> *** Starting 2 switches
> s1 (1.00Mbit 100ms delay) s2 (1.00Mbit 100ms delay) ...(1.00Mbit 100ms delay) (1.00Mbit 100ms delay) 
> *** Activating NDN-DPDK
> activate result {'data': {'activate': True}}
> activate result {'data': {'activate': True}}
> *** Creating faces and FIB entries
> faceP result {'data': None, 'errors': [{'message': 'no feasible impl, check NDN-DPDK service logs for details', 'locations': [{'line': 3, 'column': 9}], 'path': ['createFace']}]}
> Traceback (most recent call last):
>   File "ndntopo.py", line 99, in <module>
>     'nexthops': [faceP['data']['createFace']['id']]
> TypeError: 'NoneType' object is not subscriptable

Also when I check the docker logs mn.p
I get some errors related to Hugepages though the script is able to set the hugepages.
Is there still something I am missing from my steps.

> {"level":"info","ts":1633689927.2765963,"logger":"main","msg":"NDN-DPDK service starting","version":"v0.0.0-20211007141541-9160e6d38d82","uid":0,"linux":"5.11.0-37-generic","dpdk":"DPDK 21.08.0","spdk":"SPDK v21.07"}
> {"level":"info","ts":1633689927.2772338,"logger":"main","msg":"GraphQL HTTP server starting","listen":":3030"}
> {"level":"info","ts":1633689928.6294498,"logger":"main","msg":"activate start","role":"forwarder"}
> {"level":"info","ts":1633689928.7094574,"logger":"DPDK","msg":"EAL: 4096 hugepages of size 2097152 reserved, but no mounted hugetlbfs found for that size"}
> {"level":"warn","ts":1633689928.7095907,"logger":"DPDK","msg":"EAL: No available 1048576 kB hugepages reported"}
> {"level":"warn","ts":1633689928.7096412,"logger":"DPDK","msg":"EAL: No free 1048576 kB hugepages reported on node 0"}
> {"level":"warn","ts":1633689928.709694,"logger":"DPDK","msg":"EAL: No available 1048576 kB hugepages reported"}
> {"level":"error","ts":1633689928.7097754,"logger":"DPDK","msg":"EAL: Cannot open VFIO container /dev/vfio/vfio, error 2 (No such file or directory)"}
> {"level":"info","ts":1633689928.7098334,"logger":"DPDK","msg":"EAL: VFIO support could not be initialized"}
> {"level":"warn","ts":1633689928.8126576,"logger":"DPDK.0","msg":"TELEMETRY: No legacy callbacks, legacy socket not created"}
> {"level":"info","ts":1633689928.812654,"logger":"ealinit","msg":"EAL ready","args":"--lcores \\(0,1,2,3,4,5\\)@\\(0,1,2,3,4,5,6,7\\) --socket-limit 4096 --in-memory --single-file-segments -d /usr/local/lib/dpdk/pmds-21.3 --no-pci","main":0,"workers":[1,2,3,4,5],"sockets":[0]}
> {"level":"info","ts":1633689928.8290143,"logger":"SPDK.0","msg":"SPDK logger ready"}
> {"level":"info","ts":1633689928.8490164,"logger":"pktmbuf","msg":"decreasing Dataroom","key":"PAYLOAD","oldDataroom":11285,"newDataroom":9128}
> {"level":"info","ts":1633689928.8490958,"logger":"ealthread","msg":"lcore requested","role":"CRYPTO","req-socket":"any","lc":1}
> {"level":"info","ts":1633689928.8491085,"logger":"ealthread","msg":"lcore requested","role":"FWD","req-socket":"any","lc":2}
> {"level":"info","ts":1633689928.8491223,"logger":"ealthread","msg":"lcore requested","role":"RX","req-socket":"any","lc":3}
> {"level":"info","ts":1633689928.8491352,"logger":"ealthread","msg":"lcore requested","role":"TX","req-socket":"any","lc":4}
> {"level":"info","ts":1633689928.849164,"logger":"ealthread","msg":"lcore requested","role":"FWD","req-socket":"any","lc":5}
> {"level":"info","ts":1633689928.8982754,"logger":"Pcct","msg":"Init","pcct":"0x1183affc00"}
> {"level":"info","ts":1633689928.8983326,"logger":"Pit","msg":"Init","pit":"0x1183affc20","pcct":"0x1183affc00"}
> {"level":"info","ts":1633689928.8983564,"logger":"MinTmr","msg":"New","sched":"0x1183ed8a40","slots":"4096","interval":"116333333","cb":"0x970e70"}
> {"level":"info","ts":1633689928.8983808,"logger":"Cs","msg":"Init","cs":"0x1183affc80","arc":"0x1183affc80","pcct":"0x1183affc00","cap-md":"32767","cap-mi":"32767"}
> {"level":"info","ts":1633689929.03248,"logger":"Pcct","msg":"Init","pcct":"0x119023dc40"}
> {"level":"info","ts":1633689929.0325313,"logger":"Pit","msg":"Init","pit":"0x119023dc60","pcct":"0x119023dc40"}
> {"level":"info","ts":1633689929.032562,"logger":"MinTmr","msg":"New","sched":"0x1190229080","slots":"4096","interval":"116333333","cb":"0x970e70"}
> {"level":"info","ts":1633689929.0325897,"logger":"Cs","msg":"Init","cs":"0x119023dcc0","arc":"0x119023dcc0","pcct":"0x119023dc40","cap-md":"32767","cap-mi":"32767"}
> {"level":"info","ts":1633689929.0477326,"logger":"eal","msg":"vdev initialized","name":"crypto_openssl_K0000000000000011","args":"max_nb_queue_pairs=1,socket_id=0","socket":0}
> {"level":"info","ts":1633689929.0480247,"logger":"FwCrypto.1","msg":"Run","fwc":"0x1190226940","input":"0x1190226480","pool":"0x11c867a280","cryptodev":"0-0"}
> {"level":"info","ts":1633689929.0480618,"logger":"FwFwd.2","msg":"Run","fwd-id":"0","fwd":"0x118046f4c0","fib":"0x1190228f00","pit":"0x1183affc20","cs":"0x1183affc80","crypto":"0x1190226480"}
> {"level":"info","ts":1633689929.048148,"logger":"FwFwd.5","msg":"Run","fwd-id":"1","fwd":"0x119023e100","fib":"0x1190228f00","pit":"0x119023dc60","cs":"0x119023dcc0","crypto":"0x1190226480"}
> {"level":"info","ts":1633689929.0482023,"logger":"main","msg":"activate success","role":"forwarder"}
> {"level":"error","ts":1633689929.4563684,"logger":"ethvdev","msg":"ethtool.GetChannels error","netif":"P-eth0","ifindex":31,"error":"operation not supported"}
> {"level":"info","ts":1633689929.4572797,"logger":"eal","msg":"vdev initialized","name":"net_af_xdp_P-eth0","args":"start_queue=0,queue_count=1,xdp_prog=/usr/local/lib/bpf/ndndpdk-xdp-map0.o,iface=P-eth0","socket":"any"}
> {"level":"info","ts":1633689929.459304,"logger":"ethface","msg":"port opened","port":0}
> {"level":"info","ts":1633689929.459675,"logger":"ethface","msg":"impl init error, trying next impl","port":0,"impl":"RxMemif","error":"cannot use RxMemif on non-memif port"}
> {"level":"info","ts":1633689929.459702,"logger":"ethface","msg":"impl init error, trying next impl","port":0,"old-impl":"RxMemif","impl":"RxFlow","error":"cannot use RxFlow on virtual device"}
> {"level":"warn","ts":1633689929.4597273,"logger":"ethdev","msg":"rte_eth_dev_reset error","id":0,"name":"net_af_xdp_P-eth0","error":"95 Operation not supported"}
> libbpf: Netlink-based XDP prog detected, please unload it in order to launch AF_XDP prog
> {"level":"warn","ts":1633689929.4619825,"logger":"ethdev","msg":"rte_eth_dev_reset error","id":0,"name":"net_af_xdp_P-eth0","error":"95 Operation not supported"}
> {"level":"warn","ts":1633689929.462004,"logger":"ethdev","msg":"Start error","id":0,"name":"net_af_xdp_P-eth0","mtu":"unchanged","rxq":1,"txq":1,"promisc":true,"error":"rte_eth_rx_queue_setup(0,0) 22 Invalid argument"}
> {"level":"info","ts":1633689929.4620163,"logger":"ethface","msg":"impl init error, trying next impl","port":0,"old-impl":"RxFlow","impl":"RxTable","error":"rte_eth_rx_queue_setup(0,0) 22 Invalid argument"}
> {"level":"warn","ts":1633689929.4620323,"logger":"ethdev","msg":"rte_eth_dev_reset error","id":0,"name":"net_af_xdp_P-eth0","error":"95 Operation not supported"}
> {"level":"warn","ts":1633689929.4620469,"logger":"ethface","msg":"no feasible impl","port":0,"old-impl":"RxTable"}
> {"level":"warn","ts":1633689929.4620621,"logger":"iface","msg":"start error","id":40316,"socket":0,"mtu":1514,"locator":{"local":"02:60:18:6d:b0:10","remote":"02:60:18:6d:b0:20","port":"net_af_xdp_P-eth0"},"error":"no feasible impl, check NDN-DPDK service logs for details"}
> {"level":"error","ts":1633689929.4621067,"logger":"DPDK.0","msg":"xsk_configure(): Failed to create xsk socket."}
> {"level":"error","ts":1633689929.4621491,"logger":"DPDK.0","msg":"eth_rx_queue_setup(): Failed to configure xdp socket"}
> 


Thanks for your support.

**Comment by rohansuri1996** [comment]
Hi, 
After  > .vdevConfig.xdp.disabled=true the above code didn't give any error but still P and Q cannot ping each other.

I get the following error-

P ndndpdk-godemo pingclient --name /Q

> 2021/10/14 11:22:37 uplink opened
> 2021/10/14 11:22:38   0.00% E D3926043FAB8809A Interest expired
> 2021/10/14 11:22:38   0.00% E D3926043FAB8809B Interest expired
> 2021/10/14 11:22:38   0.00% E D3926043FAB8809C Interest expired

So i tried some things like creating new faces. So I executed one of the container and ran the above command again but got the same error. So I thought maybe the script wasn't able to create faces and thats why interest packet cannot go anywhere and expires before any data transfer.

So I tried creating faces from inside the container and execute the following command  ` ndndpdk-ctrl create-ether-face --local 02:00:00:00:00:01 --remote 02:00:00:00:00:02`
But i wasn't able to create faces.

>  2021/10/14 11:35:39 graphql: EthDev not found

Does this means there is some sort of Hardware incompatibility or do I have to mention someting in the code.

Thank you for your support.

**Comment by yoursunny** [comment]
> {"level":"info","ts":1634210090.3965607,"logger":"eal","msg":"vdev initialized","name":"net_af_xdp_P-eth0","args":"queue_count=1,xdp_prog=/usr/local/lib/bpf/ndndpdk-xdp-map0.o,iface=P-eth0,start_queue=0","socket":"any"}
> libbpf: Netlink-based XDP prog detected, please unload it in order to launch AF_XDP prog

This is weird.
XDP is disabled in locator yet net\_af\_xdp driver is still selected.

I need to check if there's some bug causing disabling XDP to become ineffective.

**Comment by rohansuri1996** [comment]
Everything is working. Thanks.
