### ISSUE TITLE
insertFibEntry replacing already inserted FibEntry

### ISSUE THREAD

**Issue by rohansuri1996** [usnistgov/ndn-dpdk#48]
Hi,

I have a method to create face-
  ```def createEtherFace(self,  localMAC, remoteMAC, name):  # returns face ID
        info('*** Creating face\n')
        face = self.graphQLClient.fetch("""
            mutation createFace($locator: JSON!) {
                createFace(locator: $locator) {
                    id
                }
            }
        """, {
            'locator': {
                'scheme': 'ether',
                'local': localMAC ,
                'remote': remoteMAC,
                'vdevConfig': {
                'xdp': {
                    'disabled': True
                }
            }
            }
        }
        )
        self.faces[name] = face
        info('***face result %s\n' % face)

```
and a method to insert the Fib Entries-

 ```
def insertFibEntry(self, prefix, name): # returns FIB entry ID
        fib = self.graphQLClient.fetch("""
            mutation insertFibEntry($name: Name!, $nexthops: [ID!]!) {
                insertFibEntry(name: $name, nexthops: $nexthops) {
                    id
                }
            }
        """, {
            'name': "/"+prefix ,
            'nexthops': [self.faces[name]['data']['createFace']['id']]
        })
        info('***fib result %s\n' % fib)
        info('***prefix is %s'% "'/"+prefix+"'"+ '\n')
        fib_id = fib['data']['insertFibEntry']['id']
        print(fib_id)
        return fib_id #this is returning fib id which we can store in a dictionary or list for further actions

```
These methods are called somewhat like this-
```
Q.createEtherFace('02:60:18:6d:b0:05','02:60:18:6d:b0:06', 'faceQS') #Q to S to make face
fib_ids['V_QT'] = Q.insertFibEntry('V', 'faceQT') #to insert fib entry where V is prefix and faceQT is next hop
fib_ids['V_QS'] = Q.insertFibEntry('V', 'faceQS')
```

1. The problem is my second method call to insertFibEntry is replacing the first fibInsertion though they are with different faces (faceQT and faceQS)
2. Also, I have a continuous question if a host has 2 fib entries for the same data object then which hop does it choses?

**Comment by yoursunny** [comment]
> my second method call to insertFibEntry is replacing the first fibInsertion though they are with different faces (faceQT and faceQS)

This behavior is by design.
`mutation insertFibEntry` is effectively **insert or overwrite FIB entry**.
A subsequent call on the same prefix would replace the previous set of nexthops.

To have two nexthops, you should include both faces in the nexthop set.
The GraphQL argument should be something like:

```json
{
  "name": "/V",
  "nexthops": ["ID-of-faceQT", "ID-of-faceQS"]
}
```

---

> if a host has 2 fib entries for the same data object then which hop does it choses?

The forwarding strategy will forward to the nexthop that it believes to be the most likely to successfully retrieve the Data quickly.
Read [On the Role of Routing in Named Data Networking](https://named-data.net/publications/role_of_routing_ndn/) on what forwarding strategy does.
From forwarding strategy point of view, the nexthops in the FIB is consider "routing".

**Comment by rohansuri1996** [comment]
ok I understand now but is it possible to delete a hop from nexthop or add a new hop? I saw the graphQL docs and the delete mutation takes the object id to delete fib entry or face.

**Comment by yoursunny** [comment]
> is it possible to delete a hop from nexthop or add a new hop?

To add a nexthop to an existing FIB entry, call `mutation insertFibEntry` with an updated FIB entry that contains both the existing nexthops and the new nexthop.

To delete a nexthop,

* If the updated FIB entry should no longer exist, call `mutation delete` to delete the FIB entry.
* If the updated FIB entry should still exist, call `mutation insertFibEntry` with an updated FIB entry that contains the remaining nexthops.

**Comment by rohansuri1996** [comment]
Thanks, that's what we thought and planned to execute.

**Comment by rohansuri1996** [comment]
def insertFibEntry(self, prefix, names): # returns FIB entry ID
        ids = [ self.faces[name]['data']['createFace']['id'] for name in names]

        fib = self.graphQLClient.fetch("""
            mutation insertFibEntry($name: Name!, $nexthops: [ID!]!) {
                insertFibEntry(name: $name, nexthops: $nexthops) {
                    id
                }
            }
        """, {
            'name': "/"+prefix ,
            'nexthops': ids
        })
        info('***fib result %s\n' % fib)
        info('***prefix is %s'% "'/"+prefix+"'"+ '\n')
        fib_id = fib['data']['insertFibEntry']['id']
        print(fib_id)
        return fib_id #this is returning fib id which we can store in a dictionary or list for further actions
