### ISSUE TITLE
Not issue: Recommendation to add to the docs to clone the project rather than downloading zip

### ISSUE THREAD

**Issue by rohansuri1996** [usnistgov/ndn-dpdk#52]
I downloaded the zip file of the project but I wanted to mention and contribute that this is not the correct way to download the project. 

Its silly from my side but you can mention in the documents to clone the project rather than downloading zip. If you download zip then it throws an error while building the docker container.

**Comment by yoursunny** [comment]
You can `docker build` from an URI.
No downloading or cloning necessary.
https://docs.docker.com/engine/reference/commandline/build/
