### ISSUE TITLE
Cant compile older version

### ISSUE THREAD

**Issue by rohansuri1996** [usnistgov/ndn-dpdk#55]
Hi so I couldn't get the new process of making faces on my testbed so I git checked out to the older version but I am getting this error while building the docker image

> [513/2457] Compiling C object lib/librte_vhost.a.p/vhost_vhost_crypto.c.o
> ninja: build stopped: subcommand failed.
> The command '/bin/sh -c sh -c 'apt-get -y -qq update' &&     apt-get -y -qq install --no-install-recommends ca-certificates curl jq lsb-release ${APT_PKGS} &&     env SKIPROOTCHECK=1 ${DEPENDS_ENV} /root/ndndpdk-depends.sh --dir=/root/ndndpdk-depends -y ${DEPENDS_ARGS} &&     rm -rf /root/ndndpdk-depends' returned a non-zero code: 1
> 

I have tried things like uninstalling the dependencies and reinstalling them

**Comment by yoursunny** [comment]
Only the latest version is supported.

The Docker image is self-contained and you don't need to manually install dependencies.

**Comment by rohansuri1996** [comment]
Solution- Use bit newer version of ndn-dpdk.

**Comment by yoursunny** [comment]
I guess you picked a commit that doesn't compile.
This occasionally happens due to dependency breakage.

**Comment by rohansuri1996** [comment]
> I guess you picked a commit that doesn't compile. This occasionally happens due to dependency breakage.

Yes. I figured out in the hard way XD
