### ISSUE TITLE
Change of strategy on an event happening

### ISSUE THREAD

**Issue by rohansuri1996** [usnistgov/ndn-dpdk#56]
Question\doubt- So moving forward I am trying to develop another mechanism in which the ndn-dpdk changes its strategy of forwarding interests.
For example if there is a ping going on between two hosts and then a trigger happens and the packet drop of 20% starts happening, then my mechanism is to be programmed in such a way that it can change the strategy from random maybe to roundrobin.

So my question is do you have any lead for me-

1. How can I drop the packet by 20% when the ping is already going on?
2. Would I be able to change the strategy after the packet drop starts happening?

I hope these questions are allowed in the issues, if not please also let me know. I want this mechanism to be part of bigger airborne network test bed.

**Comment by yoursunny** [comment]
> How can I drop the packet by 20% when the ping is already going on?

The traffic generator producer can drop Interests with certain probability.
If you are using another producer, this needs to be programmed into the producer.

---

> after the packet drop starts happening, change the strategy from random to roundrobin

This should be coded within a single strategy:

1. This strategy shall have both behaviors.
2. The strategy should measure, based on Interests and Data received recently, to determine which behavior should be chosen for each Interest forwarding.
3. Measurement information can be stored in FIB entry scratch area.

An example is the fastroute strategy.
It has both multicast and unicast behaviors.
It starts with multicast, and then learn the fastest nexthop and switch to unicast.

In NFD you can find ASF and self-learning strategies that also use measurements extensively.

**Comment by yoursunny** [comment]
Forwarder does not willingly drop traffic.
Only the traffic generator can drop (i.e. not respond to) incoming Interests.

**Comment by rohansuri1996** [comment]
> Forwarder does not willingly drop traffic. Only the traffic generator can drop (i.e. not respond to) incoming Interests.

Yes I got it but I can generate a similar method to start the traffic generator also. Right?

**Comment by yoursunny** [comment]
The traffic generator is also activated via GraphQL.
See `docs/trafficgen.md`.

**Comment by rohansuri1996** [comment]
> The traffic generator is also activated via GraphQL. See `docs/trafficgen.md`.

So from what I understand for traffic generation 

1. first we have to activate the traffic generator and 
2. then start the traffic
```

def activateTrafficGen(self):
        info('*** Generating traffic\n')
        trafficActivate = self.graphQLClient.fetch("""
                mutation activate($arg: JSON!) {
                    activate(trafficgen: $arg)
                }
            """, {
                'arg': {
                    'eal': {
                        'cores': [6, 7, 8, 9, 24, 25, 26, 27],
                    },
                    'mempool': {
                        'DIRECT': {'capacity': 65535, 'dataroom': 9128},
                        'INDIRECT': {'capacity': 65535},
                    },
                }
            })
        info('Traffic Activate result %s\n' % trafficActivate)
```
I used mutation to activate the trafficgenerator but its says-

> {'message': 'ndndpdk-svc is already activated', 'locations': [{'line': 3, 'column': 21}], 'path': ['activate']}]

note: I have similarly activated forwarder

**Comment by rohansuri1996** [comment]
> The traffic generator is also activated via GraphQL. See `docs/trafficgen.md`.

Since I have many ndndpdk hosts, currently I have them all activated as forwarders and I just use ping to generate traffic.
Now my problem is how to use them as traffic generators, I tried activating them as traffic generators but then I couldn't do fib entries.

Should I add two more hosts at the endpoints and use them  as traffic generators?

**Comment by yoursunny** [comment]
See [RFC8793](https://datatracker.ietf.org/doc/html/rfc8793) terminology.
Traffic generator is a combination of ICN consumer and ICN producer.

> Should I add two more hosts at the endpoints and use them as traffic generators? and the forwarders are basically intermediate nodes?

Yes you can.
