### ISSUE TITLE
No such file or directory- when loading the strategy

### ISSUE THREAD

**Issue by rohansuri1996** [usnistgov/ndn-dpdk#59]
I was experimenting a new strategy. I made a new strategy like other strategies and added to my folder and built my ndn-dpdk container again.

I am loading the strategy with something like this-

` ndndpdk-ctrl load-strategy --elffile /usr/local/lib/bpf/ndndpdk-strategy-random.o`

 but it throws me an error 

>  no such file or directory

Do you know why I am getting this error, I assume the code has some error and random.c file cannot compile.

Code for strategy
```
/**
 * @file
 * If a nexthop is unusable (face down, supression, etc), packet is lost.
 */
#include "api.h"

typedef struct FibEntryInfo
{
  uint8_t nextNexthopIndex;
} FibEntryInfo;

SUBROUTINE uint64_t
RxInterest(SgCtx* ctx)
{
  FibEntryInfo* fei = SgCtx_FibScratchT(ctx, FibEntryInfo);
  if (fei->nextNexthopIndex >= ctx->fibEntry->nNexthops) {
    fei->nextNexthopIndex = (unsigned)rand() % (unsigned)((ctx->fibEntry->nNexthops + 1));
  }

  SgFibNexthopIt it;
  for (SgFibNexthopIt_Init2(&it, ctx); SgFibNexthopIt_Valid(&it); SgFibNexthopIt_Next(&it)) {
    if (it.i < fei->nextNexthopIndex) {
      continue;
    }
    fei->nextNexthopIndex = (unsigned)rand() % ((unsigned)(ctx->fibEntry->nNexthops + 1));
    return SgForwardInterest(ctx, it.nh);
  }
  return 9100;
}

uint64_t
SgMain(SgCtx* ctx)
{
  switch (ctx->eventKind) {
    case SGEVT_INTEREST:
      return RxInterest(ctx);
    default:
      return 9000;
  }
}
```

**Comment by yoursunny** [comment]
> ` ndndpdk-ctrl load-strategy --elffile /usr/local/lib/bpf/ndndpdk-strategy-random.o`
> 
> but it throws me an error
> 
> > no such file or directory

Does this file exist in the filesystem?
If you are running `ndndpdk-ctrl` in a container, the file must exist (compiled into the image or mounted as volume) in the container where the `ndndpdk-ctrl` process is running.

The GraphQL `loadStrategy` mutation accepts the strategy ELF object as binary string.
It is the client (e.g., `ndndpdk-ctrl`) that reads the file from its filesystem.

**Comment by rohansuri1996** [comment]
I see the file 

> ndndpdk-strategy-random.o

in the file system.

Just one thing when I didn't add unsigned to my above code it threw me an error-

> Unsupported signed division for DAG

I did not understand this error so I added unsigned to my variables. This could be some problem?

**Comment by rohansuri1996** [comment]
Its the rand() function which is not working.
