### ISSUE TITLE
Install fail with "mk/update-list.sh dirname: miss operand" 

### ISSUE THREAD

**Issue by suitgo** [usnistgov/ndn-dpdk#65]
When compile with command `make` I got faild, the info is bellow:
```shell
~$ make NDNDPDK_MK_RELEASE=1
mk/update-list.sh
dirname: miss operand
Please try "dirname --help" get more information
make: *** [Makefile:12：csrc/meson.build] Error 123
```

And I checked that this was failed when run 
```bash
git grep -l '^import "C"$' '**/*.go' | xargs dirname | sort -u | sed "s|.*|'\0'|" | paste -sd,
```
Is there any other tools I missed?

My git version is:
```shell
~$ git --version
git version 2.34.1
```

My system is Ubuntu 22.04 amd64

**Comment by yoursunny** [comment]
What's the output of this command?

```bash
git grep -l '^import "C"$' '**/*.go'
```

**Comment by suitgo** [comment]
Nothing will show with this command:

git grep -l '^import "C"$' '**/*.go'

if only with '^import "C"$' will show one line:

~git grep -l '^import "C"$'

if only with  '**/*.go' will show all the files:

~git grep -l '**/*.go'
.dockerignore
.github/workflows/build.yml
.gitignore
Dockerfile
LICENSE.md
Makefile
README.md
app/fetch/README.md
app/fetch/fetcher.go
app/fetch/fetchtest/fetcher_test.go
app/fetch/fetchtest/helper.go
app/fetch/fetchtest/logic_ctest.go
mk/cgoflags.sh
...

**Comment by yoursunny** [comment]
I cannot reproduce.
Maybe something is wrong with your git config or git clone?

```shell
$ docker run -it --rm ubuntu:jammy

root@aeafa78113b8:/# apt update && apt install git

root@aeafa78113b8:/# git clone https://github.com/usnistgov/ndn-dpdk.git

root@aeafa78113b8:/# cd ndn-dpdk/

root@aeafa78113b8:/ndn-dpdk# git grep -l '^import "C"$' '**/*.go'
app/fetch/fetcher.go
app/fetch/fetchtest/logic_ctest.go
app/fetch/fetchtest/tcpcubic_ctest.go
app/fetch/fetchtest/window_ctest.go
app/fetch/logic.go
app/fetch/task.go
app/fetch/worker.go
app/fileserver/worker.go
```

**Comment by yoursunny** [comment]
> I have checked with Ubuntu and windows

Does this mean the NDN-DPDK codebase checkout is on a Windows filesystem or in Windows Subsystem for Linux container?

**Comment by suitgo** [comment]
> NDN-DPDK service will not work on Windows or WSL, even if you manage to compile it. You need to use a Linux machine, or at least a full virtual machine (VirtualBox, VMware, Hyper-V, etc; not WSL container).
> 
> NDN-DPDK codebase checkout needs to reside on a Linux filesystem that preserves Unix permission bits. It cannot be on Windows filesystem, NFS, VM shared folder, etc.

Is there any way without using git to clone If I only download the code with zip ?
My Linux is full virtual machine(VMware), but can nont connect with github, So I git clone the code in windows system and then copy to Linux.

**Comment by yoursunny** [comment]
> My Linux is full virtual machine(VMware)

That should work, as long as the git repository is on Linux filesystem (such as ext4, xfs, btrfs).

> can nont connect with github,

Why?

**Comment by suitgo** [comment]
> > My Linux is full virtual machine(VMware)
> 
> That should work, as long as the git repository is on Linux filesystem (such as ext4, xfs, btrfs).
> 
> > can nont connect with github,
> 
> Why?
> 
Our some machine has no right to connect the public net.

> > I git clone the code in windows system and then copy to Linux.
> 
> It will not work because checking out the codebase on a Windows filesystem means you have lost the Unix permission bits.

**Comment by suitgo** [comment]
Thanks a lot for helping.
I have cloned with another Linux system and then copy to the target system.
And I also suggest for supporting a way with offline system ex.

**Comment by yoursunny** [comment]
> Our some machine has no right to connect the public net.

If you don't have Internet at all, you won't be able to build NDN-DPDK on this machine.
Apart from the initial clone, the Go compiler needs to download Go modules, and PNPM needs to download Node.js packages.

To install NDN-DPDK on a machine without Internet:

1. On a server with Internet access, build a NDN-DPDK Docker container (see instructions in `docs/Docker.md`). Be sure to set `--arch` flag to match the CPU model on the target machine.
2. Run `docker save` to export the container image to a tarball, copy to the offline machine, run `docker load` to import the tarball.
3. You can then run NDN-DPDK Docker container on the offline machine.
