### ISSUE TITLE
Outdated documentation in appinit

### ISSUE THREAD

**Issue by Pesa** [usnistgov/ndn-dpdk#7]
It seems that `appinit/README.md` contains several references to functions(?) that no longer exist in the codebase, such as `RegisterMempool` and `EnableCreateFace`.

**Comment by yoursunny** [comment]
I'm doing some cleanup throughout the codebase.

Functionality of `appinit` are being moved down to lower level packages:

* [X] mempool configuration goes to `dpdk/pktmbuf` and `ndni`.
* [X] face creation goes to `iface` and `iface/createface`.
* [ ] management goes to `mgmt`.
* [ ] (most of) init-config goes to `core/initconfig`.

After that, the `appinit` package will be deleted.

**Comment by yoursunny** [comment]
Package appinit vanished in 3a54fb2c110dca190f999fc8a8fc8d49d31b2a96.
The directory still exists, until I finish refactoring TypeScript code.
