### ISSUE TITLE
how do I get the MTU to 9000

### ISSUE THREAD

**Issue by Syafaatdehaf** [usnistgov/ndn-dpdk#74]
when I do the command ```sudo ifconfig ens3 MTU 9000``` it can successfully change to 9000 MTU from the previous 1500 MTU but when creating a port it cannot use 9000 MTU and has the output as below:
```
2023/06/22 15:57:34 graphql: PacketMempool dataroom is too small for requested MTU
```
is there any documentation for this problem?

**Comment by yoursunny** [comment]
From [NDN-DPDK forwarder activation and usage](https://github.com/usnistgov/ndn-dpdk/blob/08d7daa0e15a1910f377a44e943baf265b3d2969/docs/forwarder.md) - commonly used activation parameters:

> **.mempool.DIRECT.dataroom** is the size of each packet buffer.
> The maximum Ethernet port MTU supported by the forwarder is this dataroom minus DPDK mbuf headroom (`RTE_PKTMBUF_HEADROOM`, normally 128) and Ethernet+VLAN header length (18).
> For example, to support MTU=9000, this must be set to at least 9146.

**Comment by yoursunny** [comment]
> sudo ifconfig ens3 MTU 9000

ifconfig is [deprecated in Ubuntu](https://ubuntu.com/blog/if-youre-still-using-ifconfig-youre-living-in-the-past).
You should write `sudo ip link set ens3 mtu 9000` instead.

Nevertheless, changing MTU with `iproute2` would have no effect on DPDK.
