### ISSUE TITLE
error when running the forwarder

### ISSUE THREAD

**Issue by Syafaatdehaf** [usnistgov/ndn-dpdk#77]
I want to run NDN-DPDK on 4 cores 
with the forwarder json file as below:
```js
eal: {
    coresPerNuma: {"0": 4},
    lcoresPerNuma: {"0": 1},
  },
  mempool: {
    DIRECT: { capacity: 1048575, dataroom: 9146 },
    INDIRECT: { capacity: 1048575 },
  },
  fib: {
    capacity: 4095,
    startDepth: 8,
  },
  pcct: {
    pcctCapacity: 65535,
    csMemoryCapacity: 20000,
    csIndirectCapacity: 20000,
  },
```

Error when running NDN-DPDK on the forwarder
when run has the following error:
```text
Started NDN-DPDK service on 127.0.0.1:3030.
("level": "info", "ts": 1688473076.0902858, "logger": "main", "msg": "Graphol HTTF server starting", "listen": "127.0.0.1:3030")
"ts": 1688473076.4093182, "logger": "main", "nsa": "activate start" "role": "forwarder"!
("level": "info", "ts": 1688473076.5410721, "logger": "DPDK", "msg": "EAL: 5120 hugepages of size 2097152 reserved, but no mounted hugetibfs found
size")
("level": "warn", "ts": 1680473076.5449055, "logger": "DPDK.0", "msg": "TELEMETRY: No legacy callbacks, legacy socket not created"!
```

when I check hugepages:
```text
Node Pages Size Total
0    5120  2Mb    10Gb
0    2     1Gb    2Gb
```

is there a solution to this error?

**Comment by yoursunny** [comment]
> no mounted hugetibfs found

Hugepages are not setup correctly.
Please re-run `dpdk-hugepages.py` script.

> lcoresPerNuma: {"0": 1}

Forwarder will not start with only 1 lcore; at least 5 lcores are required.
These lcores are created as threads mapped to the physical cores.

> I want to run NDN-DPDK on 4 cores

It's possible with the lcores configurations, but you won't get much benefits for running NDN-DPDK.
Low end hardware is better served with the YaNFD forwarder.
