### ISSUE TITLE
ModuleNotFoundError: No module named 'plugins'

### ISSUE THREAD

**Issue by benwallace2** [usnistgov/ndn-dpdk#78]
Hello,

I am encountering an error while trying to run the fileserver.py script. 

```
Traceback (most recent call last):
  File "/home/fabric/work/ndn/fabric/ndndpdk/fileserver.py", line 9, in <module>
    import v4pub
  File "/home/fabric/work/ndn/fabric/ndndpdk/v4pub.py", line 12, in <module>
    from plugins import Plugins
ModuleNotFoundError: No module named 'plugins'
```

I've read the FABRIC NDN-DPDK Experiments [README](https://github.com/yoursunny/fabric/blob/main/ndndpdk/README.md), but there doesn't seem to be any explicit mention of the plugins module or how to install it.

One solution I've tried is installing [plugins.py](https://github.com/fabric-testbed/jupyter-examples/blob/master/fabric_examples/beta_functionality/rel1.4/plugins.py) as mentioned in the FABRIC IPv4 Internet Access
[README](https://github.com/yoursunny/fabric/blob/main/ipv4/README.md).
However, this did not work and resulted in another error:

```
Traceback (most recent call last):
  File "/home/fabric/work/ndn/fabric/ndndpdk/fileserver.py", line 9, in <module>
    import v4pub
  File "/home/fabric/work/ndn/fabric/ndndpdk/v4pub.py", line 12, in <module>
    from plugins import Plugins
  File "/home/fabric/work/ndn/fabric/ndndpdk/plugins.py", line 1, in <module>
NameError: name 'false' is not defined. Did you mean: 'False'?
```

Any help would be greatly appreciated. Thank you!

**Comment by yoursunny** [comment]
> One solution I've tried is installing [plugins.py](https://github.com/fabric-testbed/jupyter-examples/blob/master/fabric_examples/beta_functionality/rel1.4/plugins.py) as mentioned in the FABRIC IPv4 Internet Access
> [README](https://github.com/yoursunny/fabric/blob/main/ipv4/README.md).

Yes, this is the `plugins.py` file you need.

> File "/home/fabric/work/ndn/fabric/ndndpdk/plugins.py", line 1, in
> NameError: name 'false' is not defined. Did you mean: 'False'?

[plugins.py](https://github.com/fabric-testbed/jupyter-examples/blob/eedf8ee83bbbed5977ec7f95a326d79525077488/fabric_examples/beta_functionality/rel1.4/plugins.py) does not contain the token `false`.
Are you sure you downloaded the file correctly?

**Comment by yoursunny** [comment]
`plugins.py` functionality has been merged into fablib.
I updated `v4pub.py` to no require `plugins.py` anymore.
