### ISSUE TITLE
How to fully utilize Fwd resources?

### ISSUE THREAD

**Issue by hiyouqian** [usnistgov/ndn-dpdk#84]
NDN-DPDK is an excellent work, but we encountered some difficulties while using it.

We have two servers, each with a network adapter installed. One server is activated as a forwarder, and the other is simultaneously activated as consumers and producers. However, regardless of how many names the consumers send, the traffic only goes through one FWD, and we cannot utilize the other FWDs, resulting in poor performance.
 
![ndn](https://github.com/usnistgov/ndn-dpdk/assets/137290300/20246814-256f-49c3-8812-19e291082608)

How can I configure it to utilize other Fwd resources?

The following are the configuration files for the forwarder, consumer, and producer:

Forwarder
```ts
import type { ActivateFwArgs } from "@usnistgov/ndn-dpdk";
import stdout from "stdout-stream";

const args: ActivateFwArgs = {
  eal: {
    cores: [0, 2, 4, 6, 8, 10, 12, 14],
  },
  lcoreAlloc: {
    RX: { "0": 2 },
    TX: { "0": 2 },
    FWD: { "0": 3 },
  },
  mempool: {
    DIRECT: { capacity: 1048575, dataroom: 2146 },
    INDIRECT: { capacity: 1048575 },
  },
};

stdout.write(JSON.stringify(args));
```

Consumer and Producer Pair 1
```ts
import type { ActivateGenArgs } from "@usnistgov/ndn-dpdk";
import stdout from "stdout-stream";

const args: ActivateGenArgs = {
  eal: {
    cores: [0, 2, 4, 6, 8, 10]
  },
  mempool: {
    DIRECT: { capacity: 1048575, dataroom: 9146 },
    INDIRECT: { capacity: 1048575 },
  },
};

stdout.write(JSON.stringify(args));
```
```ts
import type { TgConfig } from "@usnistgov/ndn-dpdk";
import stdout from "stdout-stream";

const cfg: TgConfig = {
  face: {
    scheme: "ether",
    local: "10:70:fd:31:f3:bc",
    remote: "10:70:fd:31:f3:bd",
    mtu: 2000,
  },
  producer: {
    patterns: [
      {
        prefix: "/abc/defgh/ijkl/202404071114",
        replies: [
          {
            payloadLen: 1000,
          },
        ],
      },
      {
        prefix: "/abc/defgh/ijkl",
        replies: [
          {
            payloadLen: 1000,
          },
        ],
      },
    ],
  },
  consumer: {
    patterns: [
      {
        weight: 5,
        prefix: "/xyz/opqrs/tuvw/202404071114",
        canBePrefix: true,
      },
      {
        weight: 95,
        prefix: "/xyz/opqrs/tuvw",
        canBePrefix: true,
      },
    ],
    interval: "0.1ms",
  },
};

stdout.write(JSON.stringify(cfg));
```

Consumer and Producer Pair 2
```ts
import type { ActivateGenArgs } from "@usnistgov/ndn-dpdk";
import stdout from "stdout-stream";

const args: ActivateGenArgs = {
  eal: {
    cores: [0, 2, 4, 6, 12, 14]
  },
  mempool: {
    DIRECT: { capacity: 1048575, dataroom: 9146 },
    INDIRECT: { capacity: 1048575 },
  },
};

stdout.write(JSON.stringify(args));
```
```ts
import type { TgConfig } from "@usnistgov/ndn-dpdk";
import stdout from "stdout-stream";

const cfg: TgConfig = {
  face: {
    scheme: "ether",
    local: "10:70:fd:31:f3:bd", 
    remote: "10:70:fd:31:f3:bc", 
    mtu: 2000,
  },
  producer: {
    patterns: [
      {
        prefix: "/xyz/opqrs/tuvw/202404071114",
        replies: [
          {
            payloadLen: 1000,
          },
        ],
      },
      {
        prefix: "/xyz/opqrs/tuvw",
        replies: [
          {
            payloadLen: 1000,
          },
        ],
      },
    ],
  },
  consumer: {
    patterns: [
      {
        weight: 5,
        prefix: "/abc/defgh/ijkl/202404071114",
        canBePrefix: true,
      },
      {
        weight: 95,
        prefix: "/abc/defgh/ijkl",
        canBePrefix: true,
      },
    ],
    interval: "0.1ms",
  },
};

stdout.write(JSON.stringify(cfg));

```

**Comment by yoursunny** [comment]
> We have two servers, each with a network adapter installed. One server is activated as a forwarder, and the other is simultaneously activated as consumers and producers.

I don't understand how you setup the topology.
If the traffic generator machine has only one Ethernet adapter, how did you start both "Consumer and Producer Pair 1" and "Consumer and Producer Pair 2"?

**Comment by hiyouqian** [comment]
This is our topology. Each adapter has two ports, each activated as a C/P pair.

![微信图片_20240429212349](https://github.com/usnistgov/ndn-dpdk/assets/137290300/523ce812-f0a0-4aac-9e82-407823e37f5e)

Between the two servers, there is a switch that modifies the packet MAC so that the MAC of the internal forwarder is not visible to external consumers/producers.

**Comment by hiyouqian** [comment]
After we set a larger **ndt.prefixLen**, the names can be dispatched to all FWD threads.

Thank you for your detailed reply!

**Comment by yoursunny** [comment]
> After we set a larger **ndt.prefixLen**, the names can be dispatched to all FWD threads.

It's fine to do this in a benchmark.

For real deployment, the NDT prefix length should be shorter than producer name prefixes.
Otherwise, Interests toward the same producer application would spread across many forwarding threads, which causes the forwarding strategy to lose effectiveness.
