### ISSUE TITLE
 rte_eal_init 95 Operation not supported | EAL: FATAL: unsupported cpu type

### ISSUE THREAD

**Issue by zjzzs100** [usnistgov/ndn-dpdk#88]
when i use "ndndpdk-svc" to Start the ndn-dpdk service,then i open a new terminal,and  "cd /usr/local/share/ndn-dpdk",and i use"cat forwarder.json | ndndpdk-ctrl activate-forwarder"to activate forwarder.it give an error:
graphql: rte_eal_init 95 Operation not supported
This system does not support "VPCLMULQDQ".
Please check that RTE_MACHINE is set correctly.
EAL: FATAL: unsupported cpu type.
{"level":"error","ts":1729349193.2158067,"logger":"DPDK","msg":"EAL: unsupported cpu type."}
{"level":"error","ts":1729349193.2159224,"logger":"ealinit","msg":"EAL init error","error":"rte_eal_init 95 Operation not supported","args":"--lcores \\(0,1,2,3,4,5\\)@\\(0,1\\) --main-lcore 3 --in-memory --single-file-segments -d /usr/local/lib/dpdk/pmds-24.1 -a 00:00.0"}
{"level":"fatal","ts":1729349193.3178642,"logger":"main","msg":"activate error","role":"forwarder","error":"rte_eal_init 95 Operation not supported"}
![E0955A4EC4FBECA97A2B9E505C616563](https://github.com/user-attachments/assets/5e7d2d95-2c3f-4a7b-b3a2-6e8876257a2f)

**Comment by yoursunny** [comment]
How did you build and install NDN-DPDK?
Importantly, did you build and install on the same machine, or is it built on one machine and copied to a different machine?

**Comment by zjzzs100** [comment]
> How did you build and install NDN-DPDK? Importantly, did you build and install on the same machine, or is it built on one machine and copied to a different machine?

yes,i removed the virtual machine to another computer。i will try to install it again on a new virtual machine

**Comment by zjzzs100** [comment]
when i install the NDN-DPDK in a VM,The error disappeared
